import {getSupabase} from './supabase.js';
import {moneyFromKurus,setStatus} from './utils.js';
import {createBusinessService,businessErrors} from './business-service.js';
const section=document.querySelector('#company'),status=document.querySelector('#business-status'),refresh=document.querySelector('#business-refresh'),retry=document.querySelector('#business-retry');
let service,data,key,pending=null,loading=false,busy=false;
const date=value=>new Intl.DateTimeFormat('tr-TR',{dateStyle:'short',timeStyle:'short',timeZone:'Europe/Istanbul'}).format(new Date(value));
const percentage=value=>new Intl.NumberFormat('tr-TR',{maximumFractionDigits:2}).format(value/100)+'%';
function el(tag,text,cls){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(cls)node.className=cls;return node;}
function controls(){refresh.disabled=loading||busy;retry.hidden=!pending;retry.disabled=loading||busy;for(const button of section.querySelectorAll('[data-action]'))button.disabled=loading||busy||!!pending||button.dataset.ready!=='true';}
function actionButton(card,label,kind,code,tier,ready){const button=el('button',label,ready?'primary':'');button.type='button';button.dataset.action=kind;button.dataset.ready=String(ready);button.addEventListener('click',()=>{if(!busy&&!loading&&!pending)action({p_kind:kind,p_code:code,p_expected_tier:tier,p_request_id:crypto.randomUUID()});});card.append(button);}
function render(){
 const summary=document.querySelector('#business-summary');summary.replaceChildren();for(const [label,value] of [['Nakit',moneyFromKurus(data.cash_kurus)],['Depo',data.warehouse_capacity+' ürün'],['Marka değeri',data.brand_value+' / 100'],['Çalışanlar',data.employees+' / '+data.employee_slots],['Şirket varlıkları',moneyFromKurus(data.business_assets_kurus)],['Seviye',String(data.level)]]){const card=el('article',undefined,'card');card.append(el('small',label,'muted'),el('strong',value));summary.append(card);}
 const effects=document.querySelector('#business-effects');effects.textContent='Marka fiyat toleransı +'+percentage(data.effects.brand_price_bps-10000)+' · Ekip dönüşüm bonusu +'+percentage(data.effects.employee_conversion_bps)+' · Reklam erişimi +'+percentage(data.effects.ad_traffic_bps)+' · Reklam dönüşümü +'+percentage(data.effects.ad_conversion_bps);
 for(const [container,kind,items,tier] of [['#business-warehouses','warehouse',data.warehouses,data.warehouse_tier],['#business-offices','office',data.offices,data.office_tier]]){
  const grid=document.querySelector(container);grid.replaceChildren();for(const item of items){const card=el('article',undefined,'card');card.append(el('span',item.tier===tier?'MEVCUT':item.tier<tier?'TAMAMLANDI':'HEDEF','tag'),el('h3',item.label),el('p',kind==='warehouse'?item.capacity+' ürün kapasitesi':item.employee_slots+' çalışan kontenjanı · +'+item.brand_bonus+' marka'),el('p',item.tier?moneyFromKurus(item.cost_kurus)+' · Seviye '+item.min_level+' · '+item.xp+' XP':'Başlangıç kademesi','muted'));
   if(item.tier===tier+1){const ready=data.level>=item.min_level&&BigInt(data.cash_kurus)>=BigInt(item.cost_kurus);actionButton(card,data.level<item.min_level?'Seviye '+item.min_level+' gerekli':ready?'Yükselt':'Yetersiz nakit',kind,'upgrade',tier,ready);}grid.append(card);}
 }
 const campaign=document.querySelector('#business-active-campaign');campaign.textContent=data.active_campaign?'Aktif: '+data.active_campaign.label+' · Bitiş '+date(data.active_campaign.ends_at)+' · İstanbul':'Aktif reklam yok. Aynı anda tek kampanya çalışır.';
 const ads=document.querySelector('#business-ads');ads.replaceChildren();for(const item of data.campaigns){const card=el('article',undefined,'card');card.append(el('h3',item.label),el('p',moneyFromKurus(item.cost_kurus)+' · '+item.minutes+' dakika'),el('p','Erişim +'+percentage(item.traffic_bps)+' · Dönüşüm +'+percentage(item.conversion_bps)+' · Kalıcı marka +'+item.brand_bonus,'muted'));const ready=data.level>=10&&!data.active_campaign&&BigInt(data.cash_kurus)>=BigInt(item.cost_kurus);actionButton(card,data.level<10?'Seviye 10 gerekli':data.active_campaign?'Kampanya sürüyor':ready?'Kampanya başlat':'Yetersiz nakit','campaign',item.code,0,ready);ads.append(card);}
 const roles=document.querySelector('#business-employees');roles.replaceChildren();for(const item of data.roles){const card=el('article',undefined,'card');card.append(el('span',item.active?'AKTİF':'SÖZLEŞME YOK','tag'),el('h3',item.label),el('p','Seviye '+item.level+' · Beceri '+item.skill+' · Dönüşüm +'+percentage(item.conversion_bps)),el('p',moneyFromKurus(item.salary_kurus)+' / 24 saat · Peşin','muted'));if(item.active){card.append(el('p','Bitiş '+date(item.paid_until)+' · İstanbul','muted'));actionButton(card,'Sözleşmeyi sonlandır · İade yok','fire',item.code,0,true);}else{const ready=data.level>=15&&data.employees<data.employee_slots&&BigInt(data.cash_kurus)>=BigInt(item.salary_kurus);actionButton(card,data.level<15?'Seviye 15 gerekli':data.employees>=data.employee_slots?'Ofis kontenjanı dolu':ready?(item.paid_until?'24 saat yenile':'24 saat işe al'):'Yetersiz nakit','hire',item.code,0,ready);}roles.append(card);}
 const history=document.querySelector('#business-history');history.replaceChildren();const labels={warehouse:'Depo yükseltmesi',office:'Ofis yükseltmesi',campaign:'Reklam',hire:'Çalışan sözleşmesi',fire:'Sözleşme sonlandırma'};for(const receipt of data.receipts){const row=el('div',undefined,'row');row.append(el('strong',labels[receipt.result.kind]),el('span',moneyFromKurus(receipt.result.cost_kurus)+' · +'+receipt.result.xp_reward+' XP'),el('small',date(receipt.created_at),'muted'));history.append(row);}if(!data.receipts.length)history.append(el('p','Henüz şirket işlemi yok.','muted'));controls();
}
async function load(){if(loading||document.querySelector('#game-shell').hidden)return;loading=true;controls();try{const client=await getSupabase();if(!client)throw new Error('Missing config');const {data:auth,error}=await client.auth.getUser();if(error||!auth.user)throw error||new Error('No user');key='tradeup:business-pending:'+auth.user.id;service=createBusinessService(client);if(!pending){try{const stored=JSON.parse(localStorage.getItem(key)||'null');if(stored&&['warehouse','office','campaign','hire','fire'].includes(stored.p_kind)&&typeof stored.p_code==='string'&&Number.isInteger(stored.p_expected_tier)&&/^[a-f0-9-]{36}$/i.test(stored.p_request_id))pending=stored;else localStorage.removeItem(key);}catch{localStorage.removeItem(key);}}data=await service.snapshot();render();if(!busy)setStatus(status,pending?'Önceki işlemi Aynı işlemi kontrol et ile doğrulayın.':'Şirket verileri güncel.','success');}catch(error){setStatus(status,businessErrors[error.code]||'Şirket bilgileri yüklenemedi. Yeniden deneyin.','error');}finally{loading=false;controls();}}
async function action(request){if(busy)return;busy=true;controls();setStatus(status,'İşlem doğrulanıyor…');try{localStorage.setItem(key,JSON.stringify(request));const receipt=await service.action(request);localStorage.removeItem(key);pending=null;await load();window.dispatchEvent(new Event('tradeup:economy-updated'));setStatus(status,'İşlem tamamlandı · '+moneyFromKurus(receipt.cost_kurus)+' · +'+receipt.xp_reward+' XP','success');}catch(error){if(businessErrors[error.code]){localStorage.removeItem(key);pending=null;setStatus(status,businessErrors[error.code],'error');}else{pending=request;setStatus(status,'İşlemin sonucu doğrulanamadı. Aynı işlemi kontrol et ile yeniden deneyin.','error');}}finally{busy=false;controls();}}
refresh.addEventListener('click',load);retry.addEventListener('click',()=>{if(pending)action(pending);});window.addEventListener('hashchange',()=>{if(location.hash==='#company')load();});window.addEventListener('tradeup:store-ready',()=>{if(location.hash==='#company')load();});window.addEventListener('tradeup:economy-updated',()=>{if(location.hash==='#company')load();});
setInterval(()=>{if(location.hash==='#company'&&!document.hidden&&!busy&&!loading)load();},30000);
