import {getSupabase} from './supabase.js';
import {moneyFromKurus,parseMoneyKurus,setStatus} from './utils.js';
const status=document.querySelector('#marketplace-status');const form=document.querySelector('#marketplace-create');const list=document.querySelector('#marketplace-listings');const owned=document.querySelector('#marketplace-owned');
let locked=true;
let loading=false,busy=false,offset=0,total=0,key,pending=null;
const errors={G0001:'Marketplace seviye 5’te açılır. İlerleme ekranından görev ve XP hedeflerini inceleyin.',M0001:'Geçerli miktar/fiyat girin.',M0002:'İlan limitine ulaşıldı.',M0003:'Ayrılmamış stok yetersiz.',M0004:'Bu ilan size ait değil.',M0005:'İlan veya miktar artık mevcut değil.',M0006:'Fiyat değişti. Listeyi yenileyin.',M0007:'Kendi ilanınızı satın alamazsınız.',M0008:'İstek kimliği farklı işlemde kullanılmış.',M0009:'Satıcı bakiye sınırına ulaştı.',W0005:'Bakiyeniz yetersiz.',W0006:'Depo kapasiteniz yetersiz.',PGRST202:'007_marketplace.sql dosyasını Supabase SQL Editor’da çalıştırın.','28000':'Giriş yapmanız gerekiyor.','42501':'İşlem için yetkiniz yok.','22P02':'İstek biçimi geçersiz.','22003':'Miktar veya fiyat sınır dışında.'};
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
async function rpc(name,args){const client=await getSupabase();if(!client)throw new Error('Config missing');const {data,error}=await client.rpc(name,args);if(error)throw error;return data;}
function disable(){for(const input of document.querySelectorAll('#marketplace button,#marketplace input,#marketplace select'))input.disabled=busy||!!pending||loading;document.querySelector('#marketplace-retry').disabled=busy||loading;document.querySelector('#marketplace-prev').disabled=busy||!!pending||loading||offset===0;document.querySelector('#marketplace-next').disabled=busy||!!pending||loading||offset+50>=total;if(locked)for(const control of document.querySelectorAll('#marketplace-create input,#marketplace-create select,#marketplace-create button,#marketplace-listings form input,#marketplace-listings form button'))control.disabled=true;}
async function action(name,args){if(busy)return;busy=true;disable();setStatus(status,'İşlem doğrulanıyor…');
 try{localStorage.setItem(key,JSON.stringify({name,args}));const result=await rpc(name,args);localStorage.removeItem(key);pending=null;document.querySelector('#marketplace-retry').hidden=true;await load();window.dispatchEvent(new Event('tradeup:economy-updated'));setStatus(status,name==='buy_marketplace_listing'?'Satın alındı · '+moneyFromKurus(result.total_kurus):name==='cancel_marketplace_listing'?'İlan iptal edildi; ayrılmış stok serbest bırakıldı.':'İlan yayınlandı.','success');}
 catch(error){if(errors[error.code]){localStorage.removeItem(key);pending=null;document.querySelector('#marketplace-retry').hidden=true;setStatus(status,errors[error.code],'error');}else{pending={name,args};document.querySelector('#marketplace-retry').hidden=false;setStatus(status,'Sonuç belirsiz. Aynı işlem kimliğiyle kontrol ederek tekrar deneyin.','error');}}
 finally{busy=false;disable();}
}
async function load(){if(loading||document.querySelector('#game-shell').hidden)return;loading=true;disable();if(!busy&&!pending)setStatus(status,'Marketplace yükleniyor…');
 try{const client=await getSupabase();const {data:auth,error}=await client.auth.getUser();if(error||!auth.user)throw error||new Error('Auth missing');key='tradeup:marketplace-pending:'+auth.user.id;
 const stored=localStorage.getItem(key);if(stored&&!pending){try{pending=JSON.parse(stored);}catch{localStorage.removeItem(key);}}
 document.querySelector('#marketplace-retry').hidden=!pending;
 let data=await rpc('my_marketplace',{p_offset:offset});total=Number(data.total);if(!total)offset=0;else if(offset>=total){offset=Math.floor((total-1)/50)*50;data=await rpc('my_marketplace',{p_offset:offset});}document.querySelector('#marketplace-fee').textContent='Komisyon: %'+(data.fee_bps/100).toLocaleString('tr-TR')+' · İlan limiti '+data.listing_limit;
 document.querySelector('#marketplace-page').textContent=(total?offset+1:0)+'–'+Math.min(offset+50,total)+' / '+total+' ilan';
 form.elements.product.replaceChildren();for(const item of data.items){const option=el('option',item.name+' · '+item.available+' adet');option.value=item.id;option.dataset.price=item.market_price_kurus;option.dataset.available=item.available;form.elements.product.append(option);}
 if(!data.items.length){const option=el('option','Ayrılmamış stok yok');option.value='';form.elements.product.append(option);}
 list.replaceChildren();owned.replaceChildren();
 if(!data.listings.length)list.append(el('p','Henüz aktif ilan yok.','muted'));
 for(const item of data.listings){const card=el('article',undefined,'card product-card');card.append(el('span',item.rarity,'tag'),el('h3',item.name),el('p',item.seller+' · '+item.quantity+' adet','muted'),el('strong',moneyFromKurus(item.price_kurus),'positive'),el('p','Tahmini piyasa '+moneyFromKurus(item.market_price_kurus),'muted'));
 const diff=(BigInt(item.price_kurus)-BigInt(item.market_price_kurus))*10000n/BigInt(item.market_price_kurus);card.append(el('p','Piyasaya göre '+(diff>0n?'+':'')+(Number(diff)/100).toLocaleString('tr-TR')+'%','muted'));
 if(item.mine)card.append(el('span','Senin ilanın','tag'));else{const buyForm=el('form',undefined,'purchase-form');const label=el('label','Adet');const input=el('input');input.type='number';input.min='1';input.max=String(item.quantity);input.step='1';input.value='1';input.required=true;input.setAttribute('aria-label',item.name+' Marketplace satın alma adedi');label.append(input);const button=el('button','Satın al','primary');button.type='submit';buyForm.append(label,button);buyForm.addEventListener('submit',event=>{event.preventDefault();if(locked||pending||busy||!buyForm.reportValidity())return;action('buy_marketplace_listing',{p_listing_id:item.id,p_quantity:Number(input.value),p_expected_price_kurus:item.price_kurus,p_request_id:crypto.randomUUID()});});card.append(buyForm);}list.append(card);}
 if(!data.owned.length)owned.append(el('p','Aktif ilanın yok.','muted'));
 for(const item of data.owned){const row=el('div',undefined,'row');row.append(el('strong',item.name+' · '+item.quantity+' adet'),el('span',moneyFromKurus(item.price_kurus)));const button=el('button','İptal et');button.type='button';button.setAttribute('aria-label',item.name+' ilanını iptal et');button.addEventListener('click',()=>{if(!pending)action('cancel_marketplace_listing',{p_listing_id:item.id});});row.append(button);owned.append(row);}
 if(!busy&&!pending)setStatus(status,'Marketplace güncel.','success');if(pending&&!busy)setStatus(status,'Önceki işlemin sonucunu Aynı işlemi kontrol et butonuyla doğrulayın.');disable();
 }catch(error){setStatus(status,errors[error.code]||'Marketplace yüklenemedi. Yeniden deneyin.','error');}finally{loading=false;disable();}
}
form.addEventListener('submit',event=>{event.preventDefault();if(locked||busy||pending||!form.reportValidity())return;try{action('create_marketplace_listing',{p_product_id:form.elements.product.value,p_quantity:Number(form.elements.quantity.value),p_price_kurus:parseMoneyKurus(form.elements.price.value),p_request_id:crypto.randomUUID()});}catch{setStatus(status,'Fiyatı 168,00 biçiminde girin.','error');}});
document.querySelector('#marketplace-refresh').addEventListener('click',load);document.querySelector('#marketplace-retry').addEventListener('click',()=>{if(pending)action(pending.name,pending.args);});
document.querySelector('#marketplace-prev').addEventListener('click',()=>{offset=Math.max(0,offset-50);load();});document.querySelector('#marketplace-next').addEventListener('click',()=>{if(offset+50<total){offset+=50;load();}});
window.addEventListener('hashchange',()=>{if(location.hash==='#marketplace')load();});window.addEventListener('tradeup:store-ready',()=>{if(location.hash==='#marketplace')load();});

window.addEventListener('tradeup:level-updated',event=>{locked=event.detail.level<5;disable();});
