import {getSupabase} from './supabase.js';
import {moneyFromKurus,setStatus} from './utils.js';
import {createProgressionService,progressionErrors} from './progression-service.js';
const status=document.querySelector('#progression-status'),missions=document.querySelector('#progression-missions'),achievements=document.querySelector('#progression-achievements'),refresh=document.querySelector('#progression-refresh'),retry=document.querySelector('#progression-retry');
let data,service,key,pending=null,loading=false,busy=false;
const integer=value=>new Intl.NumberFormat('tr-TR').format(BigInt(value));
const date=value=>new Intl.DateTimeFormat('tr-TR',{dateStyle:'short',timeStyle:'short',timeZone:'Europe/Istanbul'}).format(new Date(value));
function el(tag,text,cls){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(cls)node.className=cls;return node;}
function bar(value,target,label){const progress=el('progress');progress.max=100;const v=BigInt(value),t=BigInt(target);progress.value=Number((v>t?t:v<0n?0n:v)*10000n/t)/100;progress.setAttribute('aria-label',label);return progress;}
function metric(value,type){return ['npc_revenue','networth_kurus'].includes(type)?moneyFromKurus(value):integer(value);}
function controls(){refresh.disabled=loading||busy;retry.hidden=!pending;retry.disabled=loading||busy;for(const button of missions.querySelectorAll('button'))button.disabled=loading||busy||!!pending||button.dataset.ready!=='true';document.querySelector('#title-save').disabled=loading||busy;document.querySelector('#title-select').disabled=loading||busy;}
function render(){
 window.dispatchEvent(new CustomEvent('tradeup:level-updated',{detail:{level:data.level}}));
 for(const target of [document.querySelector('#progression-summary'),document.querySelector('#dashboard-progression')]){target.replaceChildren();target.append(el('strong','Seviye '+data.level+' · '+integer(data.xp)+' XP'));if(data.next_level_xp){const remaining=BigInt(data.next_level_xp)-BigInt(data.xp);target.append(bar(BigInt(data.xp)-BigInt(data.level_start_xp),BigInt(data.next_level_xp)-BigInt(data.level_start_xp),'Sonraki seviyeye ilerleme'),el('p','Sonraki seviyeye '+integer(remaining>0n?remaining:0n)+' XP','muted'));}else target.append(el('p','Azami seviye 50’ye ulaştın.','muted'));target.append(el('p','Aktif unvan: '+(data.active_title||'Henüz seçilmedi'),'muted'));}
 missions.replaceChildren();for(const item of data.missions){const card=el('article',undefined,'card');card.append(el('span',item.frequency==='daily'?'GÜNLÜK':'HAFTALIK','eyebrow'),el('h3',item.label),el('p',metric(item.progress,item.metric)+' / '+metric(item.target,item.metric)),bar(item.progress,item.target,item.label),el('p',item.xp_reward+' XP'+(BigInt(item.cash_reward_kurus)>0n?' · '+moneyFromKurus(item.cash_reward_kurus):'')+(item.title_reward?' · '+item.title_reward:'')+' ödül','muted'),el('small','Bitiş '+date(item.ends_at)+' · İstanbul','muted'));
  const ready=BigInt(item.progress)>=BigInt(item.target);const button=el('button',item.claimed?'Ödül alındı':ready?'Ödülü al':'Devam ediyor',ready&&!item.claimed?'primary':'');button.type='button';button.dataset.ready=String(ready&&!item.claimed);button.setAttribute('aria-label',item.label+' ödülünü al');button.addEventListener('click',()=>{if(!pending&&!busy)claim({p_mission_code:item.code,p_period_start:item.period_start});});card.append(button);missions.append(card);}
 achievements.replaceChildren();for(const item of data.achievements){const card=el('article',undefined,'card');card.append(el('span',item.unlocked?'KAZANILDI':'HEDEF','tag'),el('h3',item.label),el('p',item.description,'muted'),el('p',metric(item.progress,item.metric)+' / '+metric(item.target,item.metric)),bar(item.progress,item.target,item.label),el('small',item.xp_reward+' XP · '+(item.title||'Başarım'),'muted'));achievements.append(card);}
 const unlocks=document.querySelector('#progression-unlocks');unlocks.replaceChildren();for(const [level,name,implemented] of [[1,'Temel ticaret',true],[5,'Marketplace',true],[10,'Reklam',true],[15,'Çalışanlar',true],[20,'Gelişmiş analitik',false],[25,'Global pazarlar',false],[30,'Private label',false],[40,'Üretim',false],[50,'Şirketler grubu',false]]){const row=el('div',undefined,'row');row.append(el('strong','Seviye '+level+' · '+name),el('span',implemented?(data.level>=level?'Açık':'Kilitli'):'Yakında','tag'));unlocks.append(row);}
 const profile=document.querySelector('#profile-summary');profile.replaceChildren();profile.append(el('h2',data.username),el('p',data.store_name),el('strong','Seviye '+data.level+' · '+integer(data.xp)+' XP'),el('p',data.active_title||'Unvan seçilmedi','muted'));
 const select=document.querySelector('#title-select');select.replaceChildren();const none=el('option','Unvan gösterme');none.value='';select.append(none);for(const title of data.titles){const option=el('option',title.label);option.value=title.code;select.append(option);}select.value=data.active_title_code||'';
 const history=document.querySelector('#progression-history');history.replaceChildren();const labels={SALE:'Kârlı NPC satışı',ACHIEVEMENT:'Başarım',MISSION:'Görev',BUSINESS:'Şirket geliştirmesi'};for(const item of data.xp_history){const row=el('div',undefined,'row');row.append(el('strong',labels[item.kind]),el('span','+'+item.amount+' XP'),el('small',date(item.recorded_at),'muted'));history.append(row);}if(!data.xp_history.length)history.append(el('p','Henüz XP kaydı yok.','muted'));controls();
}
async function load(){if(loading||document.querySelector('#game-shell').hidden)return;loading=true;controls();
 try{const client=await getSupabase();if(!client)throw new Error('Missing config');const {data:auth,error}=await client.auth.getUser();if(error||!auth.user)throw error||new Error('No user');key='tradeup:mission-pending:'+auth.user.id;service=createProgressionService(client);
  const stored=localStorage.getItem(key);if(stored&&!pending){try{const request=JSON.parse(stored);if(typeof request.p_mission_code==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(request.p_period_start))pending=request;else localStorage.removeItem(key);}catch{localStorage.removeItem(key);}}
  data=await service.snapshot();render();if(!busy)setStatus(status,pending?'Önceki ödülü Aynı ödülü kontrol et butonuyla doğrulayın.':'İlerlemen güncel.','success');document.querySelector('#profile-status').textContent='Profilin güncel.';
  document.querySelector('#marketplace-level-note').textContent=data.level<5?'Marketplace seviye 5’te açılır. İlerleme ekranından XP hedeflerini görebilirsin. Mevcut ilanlarını iptal edebilirsin.':'Marketplace açık · Seviye '+data.level;
 }catch(error){const message=progressionErrors[error.code]||'İlerleme yüklenemedi. Yeniden deneyin.';setStatus(status,message,'error');document.querySelector('#profile-status').textContent=message;if(!data)document.querySelector('#dashboard-progression').replaceChildren(el('p',message,'muted'));}
 finally{loading=false;controls();}
}
async function claim(request){if(busy)return;busy=true;controls();setStatus(status,'Ödül doğrulanıyor…');
 try{localStorage.setItem(key,JSON.stringify(request));const receipt=await service.claim(request);localStorage.removeItem(key);pending=null;await load();window.dispatchEvent(new Event('tradeup:economy-updated'));setStatus(status,'Ödül alındı · '+receipt.xp_reward+' XP'+(BigInt(receipt.cash_reward_kurus)>0n?' · '+moneyFromKurus(receipt.cash_reward_kurus):''),'success');}
 catch(error){if(progressionErrors[error.code]){localStorage.removeItem(key);pending=null;setStatus(status,progressionErrors[error.code],'error');}else{pending=request;setStatus(status,'Ödülün sonucu doğrulanamadı. Aynı ödülü kontrol et ile tekrar deneyin.','error');}}
 finally{busy=false;controls();}
}
refresh.addEventListener('click',load);document.querySelector('#profile-refresh').addEventListener('click',load);retry.addEventListener('click',()=>{if(pending)claim(pending);});
document.querySelector('#title-form').addEventListener('submit',async event=>{event.preventDefault();if(busy||loading||!service)return;busy=true;controls();try{await service.title(document.querySelector('#title-select').value||null);await load();setStatus(document.querySelector('#profile-status'),'Unvan kaydedildi.','success');}catch(error){setStatus(document.querySelector('#profile-status'),progressionErrors[error.code]||'Unvan kaydedilemedi. Yenile ile mevcut seçimi kontrol edin.','error');}finally{busy=false;controls();}});
window.addEventListener('tradeup:store-ready',load);window.addEventListener('hashchange',()=>{if(['#dashboard','#progression','#profile','#marketplace'].includes(location.hash))load();});window.addEventListener('tradeup:economy-updated',load);
