import {getSupabase} from './supabase.js';
import {moneyFromKurus,parseMoneyKurus,setStatus} from './utils.js';
const errors={T0001:'İşlem bilgisi geçersiz.',T0002:'Aynı istek farklı bilgilerle kullanılamaz.',T0003:'Başka bir mağazanın tam adını girin.',T0004:'Bu teklif kapanmış veya bulunamadı.',T0005:'Seri numarası için sahip olduğunuz Rare/Epic/Legendary stok gerekir.',T0006:'Ürün zaten açık artırmada.',T0007:'Bu işlemi yalnızca ilgili taraf yapabilir.',T0008:'Kendi açık artırmanıza veya süresi bitene teklif veremezsiniz.',T0009:'Teklif, gösterilen en düşük tutarı karşılamalı.',T0010:'İade için bakiye sınırı aşılıyor. Önce oyun bakiyenizde yer açın.',T0011:'Teslim/iptal koşulları henüz oluşmadı veya teslim süresi doldu.',T0012:'Teklif değişti. Yenileyip tekrar deneyin.',T0013:'En fazla 10 açık artırmada kazanan teklifiniz olabilir.',G0001:'Ticaret seviye 5’te açılır.',M0002:'Aktif ilan/sözleşme/açık artırma limitine ulaşıldı.',M0003:'Yeterli serbest stok yok.',W0005:'Yeterli kullanılabilir oyun parası yok.',W0006:'Depoda yer yok. Teslim için stokta yer açın.',M0009:'Satıcının bakiye sınırı aşılıyor.',W0001:'Mağaza bulunamadı.','28000':'Yeniden giriş yapın.','42501':'Yetkiniz yok.','22P02':'İşlem biçimi geçersiz.',PGRST202:'012_advanced_trading.sql dosyasını Supabase SQL Editor’da çalıştırın.'};
const sections=['auction','contracts','collection'],statuses=sections.map(id=>document.querySelector('#'+id+'-status'));
let client,data,key,pending=null,loading=false,busy=false;
const date=value=>new Intl.DateTimeFormat('tr-TR',{dateStyle:'short',timeStyle:'short',timeZone:'Europe/Istanbul'}).format(new Date(value));
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function status(text,state){for(const target of statuses)setStatus(target,text,state);}
function controls(){for(const id of sections){document.querySelector('#'+id+'-refresh').disabled=loading||busy;const retry=document.querySelector('#'+id+'-retry');retry.hidden=!pending;retry.disabled=loading||busy;for(const input of document.querySelectorAll('#'+id+' [data-trade-control]'))input.disabled=loading||busy||!!pending||input.dataset.ready!=='true';}}
function button(card,label,action,payload,ready=true){const b=el('button',label,ready?'primary':'');b.type='button';b.dataset.tradeControl='';b.dataset.ready=String(ready);b.addEventListener('click',()=>{if(!pending&&!loading&&!busy)execute(action,payload);});card.append(b);}
function priceForm(card,label,action,payload,minimum){const form=el('form',undefined,'trade-form'),input=el('input');input.type='text';input.inputMode='decimal';input.required=true;input.value=(BigInt(minimum)/100n)+','+(BigInt(minimum)%100n).toString().padStart(2,'0');input.setAttribute('aria-label',label+' fiyatı');input.dataset.tradeControl='';input.dataset.ready=String(data.level>=5);const submit=el('button',label,'primary');submit.type='submit';submit.dataset.tradeControl='';submit.dataset.ready=String(data.level>=5);form.append(input,submit);form.addEventListener('submit',event=>{event.preventDefault();if(busy||loading||pending)return;try{execute(action,{...payload,amount_kurus:parseMoneyKurus(input.value)});}catch{status('Fiyatı 168,00 biçiminde girin.','error');}});card.append(form);}
function render(){const at=new Date(data.as_of).getTime();for(const id of sections)document.querySelector('#'+id+'-balance').textContent='Seviye '+data.level+' · Kullanılabilir '+moneyFromKurus(data.cash_kurus)+' · Tekliflerde bloke '+moneyFromKurus(data.escrow_kurus)+' · Komisyon %'+data.fee_bps/100;
 const collection=document.querySelector('#collection-grid');collection.replaceChildren();for(const item of data.collection){const card=el('article',undefined,'card');card.append(el('span',item.owned?'SAHİPSİN':'HEDEF','tag'),el('h3',item.name),el('p',item.rarity+' · '+item.quantity+' adet','muted'));const owned=data.items.find(x=>x.id===item.id);if(owned&&owned.available>0)button(card,'Bir adede seri numarası ver','serialize',{product_id:item.id});collection.append(card);}
 const serials=document.querySelector('#serial-grid');serials.replaceChildren();const auctionSelect=document.querySelector('#auction-serial');auctionSelect.replaceChildren();for(const item of data.serials){const card=el('article',undefined,'card');card.append(el('h3',item.name+' #'+item.serial_number.padStart(4,'0')),el('p',item.rarity+' · '+(item.auctioned?'Açık artırmada':'Koleksiyonunda'),'muted'));serials.append(card);if(!item.auctioned){const option=el('option',item.name+' #'+item.serial_number.padStart(4,'0'));option.value=item.id;auctionSelect.append(option);}}if(!data.serials.length)serials.append(el('p','Henüz seri numaralı ürününüz yok.','muted'));
 for(const input of document.querySelectorAll('#auction-create input,#auction-create select,#auction-create button')){input.dataset.tradeControl='';input.dataset.ready=String(data.level>=5&&auctionSelect.options.length>0);}
 const auctions=document.querySelector('#auction-grid');auctions.replaceChildren();for(const item of data.auctions){const card=el('article',undefined,'card');const ended=at>=new Date(item.ends_at).getTime(),expired=at>=new Date(item.claim_deadline).getTime();card.append(el('span',item.mine?'SENİN İLANIN':item.winning?'KAZANAN TEKLİFİN':'AÇIK ARTIRMA','tag'),el('h3',item.name+' #'+item.serial_number.padStart(4,'0')),el('p','Satıcı '+item.seller+' · '+item.bid_count+' teklif'),el('p','En yüksek '+moneyFromKurus(item.bid_kurus)+' · En düşük yeni teklif '+moneyFromKurus(item.minimum_kurus)),el('p','Bitiş '+date(item.ends_at)+' · İstanbul','muted'));
  if(!ended&&!item.mine)priceForm(card,'Teklif ver','auction_bid',{id:item.id},item.minimum_kurus);
  if(ended&&item.winning&&!expired){card.append(el('p','Teslim son tarihi '+date(item.claim_deadline)+' · Depoda 1 boş yer gerekir.','muted'));button(card,'Kazandığım ürünü teslim al','auction_claim',{id:item.id});}
  if(item.mine&&item.bid_count===0||expired&&(item.mine||item.winning))button(card,expired?'Teklifi iade et ve kapat':'Teklifsiz ilanı kapat','auction_cancel',{id:item.id});
  auctions.append(card);
 }if(!data.auctions.length)auctions.append(el('p','Henüz açık artırma yok. Kendi seri numaralı ürününüzle başlayabilirsiniz.','muted'));
 const select=document.querySelector('#contract-product');select.replaceChildren();for(const item of data.items.filter(x=>x.available>0)){const option=el('option',item.name+' · Serbest '+item.available);option.value=item.id;select.append(option);}
 for(const input of document.querySelectorAll('#contract-create input,#contract-create select,#contract-create button')){input.dataset.tradeControl='';input.dataset.ready=String(data.level>=5&&select.options.length>0);}
 const contracts=document.querySelector('#contract-grid');contracts.replaceChildren();const labels={pending:'Bekliyor',accepted:'Kabul edildi',declined:'Reddedildi',cancelled:'İptal edildi',expired:'Süresi doldu'};for(const item of data.contracts){const card=el('article',undefined,'card');const expired=at>=new Date(item.ends_at).getTime();card.append(el('span',labels[item.status],'tag'),el('h3',item.name+' · '+item.quantity+' adet'),el('p',item.seller+' → '+item.recipient),el('p','Birim '+moneyFromKurus(item.price_kurus)+' · Toplam '+moneyFromKurus(BigInt(item.price_kurus)*BigInt(item.quantity))),el('p','Bitiş '+date(item.ends_at)+' · İstanbul','muted'));if(item.status==='pending'){if(item.incoming&&!expired)button(card,'Sözleşmeyi kabul et','contract_accept',{id:item.id},data.level>=5);button(card,expired?'Süresi dolan stoğu serbest bırak':item.incoming?'Teklifi reddet':'Teklifi iptal et',item.incoming?'contract_decline':'contract_cancel',{id:item.id});}contracts.append(card);}if(!data.contracts.length)contracts.append(el('p','Henüz gönderdiğiniz veya aldığınız sözleşme yok.','muted'));
 const history=document.querySelector('#trade-history');history.replaceChildren();for(const receipt of data.receipts){const row=el('div',undefined,'row');const labels={serialize:'Seri numarası',auction_create:'Açık artırma oluşturma',auction_bid:'Teklif',auction_claim:'Teslim',auction_cancel:'Açık artırma kapatma',contract_create:'Sözleşme gönderme',contract_accept:'Sözleşme cevabı',contract_decline:'Sözleşme reddi',contract_cancel:'Sözleşme iptali'};row.append(el('strong',labels[receipt.action]),el('small',date(receipt.created_at),'muted'));history.append(row);}controls();
}
async function load(){if(loading||document.querySelector('#game-shell').hidden)return;loading=true;controls();try{client=await getSupabase();const {data:auth,error}=await client.auth.getUser();if(error||!auth.user)throw error||new Error('No user');key='tradeup:trading-pending:'+auth.user.id;if(!pending){try{const stored=JSON.parse(localStorage.getItem(key)||'null');if(stored&&typeof stored.p_action==='string'&&stored.p_payload&&/^[a-f0-9-]{36}$/i.test(stored.p_request_id))pending=stored;else localStorage.removeItem(key);}catch{localStorage.removeItem(key);}}const response=await client.rpc('my_advanced_trading');if(response.error)throw response.error;data=response.data;render();if(!busy)status(pending?'Önceki işlemi Aynı işlemi kontrol et ile doğrulayın.':'Ticaret ve koleksiyon güncel.','success');}catch(error){status(errors[error.code]||'Veriler yüklenemedi. Yeniden deneyin.','error');}finally{loading=false;controls();}}
async function execute(action,payload,request){if(busy)return;busy=true;controls();const args=request||{p_action:action,p_payload:payload,p_request_id:crypto.randomUUID()};status('İşlem doğrulanıyor…');try{localStorage.setItem(key,JSON.stringify(args));const {data:receipt,error}=await client.rpc('trade_action',args);if(error)throw error;localStorage.removeItem(key);pending=null;await load();window.dispatchEvent(new Event('tradeup:economy-updated'));status(receipt.status==='expired'?'Sözleşmenin süresi dolmuş. Stok serbest bırakıldı.':'İşlem tamamlandı.','success');}catch(error){if(errors[error.code]){localStorage.removeItem(key);pending=null;status(errors[error.code],'error');}else{pending=args;status('Sonuç doğrulanamadı. Aynı işlemi kontrol et ile yeniden deneyin.','error');}}finally{busy=false;controls();}}
for(const id of sections){document.querySelector('#'+id+'-refresh').addEventListener('click',load);document.querySelector('#'+id+'-retry').addEventListener('click',()=>{if(pending)execute(null,null,pending);});}
document.querySelector('#auction-create').addEventListener('submit',event=>{event.preventDefault();if(busy||loading||pending)return;const form=event.currentTarget;try{execute('auction_create',{serial_id:form.elements.serial.value,price_kurus:parseMoneyKurus(form.elements.price.value),duration_minutes:Number(form.elements.duration.value)});}catch{status('Başlangıç fiyatını kontrol edin.','error');}});
document.querySelector('#contract-create').addEventListener('submit',event=>{event.preventDefault();if(busy||loading||pending)return;const form=event.currentTarget;try{execute('contract_create',{recipient:form.elements.recipient.value.trim(),product_id:form.elements.product.value,quantity:Number(form.elements.quantity.value),price_kurus:parseMoneyKurus(form.elements.price.value)});}catch{status('Fiyatı ve adedi kontrol edin.','error');}});
window.addEventListener('hashchange',()=>{if(sections.includes(location.hash.slice(1)))load();});window.addEventListener('tradeup:store-ready',()=>{if(sections.includes(location.hash.slice(1)))load();});window.addEventListener('tradeup:economy-updated',()=>{if(sections.includes(location.hash.slice(1)))load();});setInterval(()=>{if(sections.includes(location.hash.slice(1))&&!document.hidden&&!loading&&!busy)load();},30000);
