import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
// Local PostgreSQL engine with only Supabase auth roles/uid emulated.
await db.exec(`create role anon; create role authenticated; create role service_role;
create schema auth; create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
grant usage on schema auth,public to anon,authenticated;
grant execute on function auth.uid() to anon,authenticated;`);
const uid1='11111111-1111-4111-8111-111111111111';
const uid2='22222222-2222-4222-8222-222222222222';
const uid3='33333333-3333-4333-8333-333333333333';
const uid4='44444444-4444-4444-8444-444444444444';
await db.query('insert into auth.users(id) values($1),($2),($3),($4)',[uid1,uid2,uid3,uid4]);
const first=await readFile('supabase/migrations/001_store_onboarding.sql','utf8');
const core=await readFile('supabase/migrations/002_database_core.sql','utf8');
const seed=await readFile('supabase/seed.sql','utf8');
async function asUser(uid,role='authenticated') {await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[uid]);await db.exec('set role '+role);}
async function count(table) {return (await db.query('select count(*)::int n from public.'+table)).rows[0].n;}
await db.exec(first);
await asUser(uid1);
await db.query('select public.complete_store_onboarding($1,$2)',['legacy','Legacy Store']);
await db.exec('reset role');await db.exec(core);await db.exec(seed);
assert.equal(await count('products'),50);
assert.equal(await count('profiles'),1);assert.equal(await count('stores'),1);assert.equal(await count('transactions'),1);
await asUser(uid1);
assert.equal((await db.query('select cash_kurus from public.stores')).rows[0].cash_kurus,1000000);
await db.query('select public.complete_store_onboarding($1,$2)',['ignored','Ignored']);
await asUser(uid2);
await assert.rejects(()=>db.query('select public.complete_store_onboarding($1,$2)',['LEGACY','Other Store']),e=>e.code==='23505');
await assert.rejects(()=>db.query('select public.complete_store_onboarding($1,$2)',['bad','x']),e=>e.code==='22023');
assert.equal(await count('profiles'),0);assert.equal(await count('stores'),0);
await db.query('select public.complete_store_onboarding($1,$2)',['second','Second Store']);
await db.query('select public.complete_store_onboarding($1,$2)',['second','Second Store']);
assert.equal(await count('stores'),1);assert.equal(await count('profiles'),1);assert.equal(await count('transactions'),1);
assert.equal((await db.query('select public.my_net_worth_kurus() n')).rows[0].n,'1000000');
for(const sql of ["update public.stores set cash_kurus=999999999", "update public.profiles set username='hacked'", "delete from public.transactions", "insert into public.inventory(store_id,product_id,quantity,average_cost_kurus) select id,'00000000-0000-4000-8000-000000000001',1,1 from public.stores"]) await assert.rejects(()=>db.exec(sql),e=>e.code==='42501');
await asUser('', 'anon');
await assert.rejects(()=>db.query('select public.complete_store_onboarding($1,$2)',['anon','Anonymous Store']),e=>e.code==='42501');
await asUser('');
await assert.rejects(()=>db.query('select public.complete_store_onboarding($1,$2)',['anon','Anonymous Store']),e=>e.code==='28000');
await db.exec('reset role');
await assert.rejects(()=>db.exec('update public.transactions set amount_kurus=1'),e=>e.code==='55000');
await assert.rejects(()=>db.exec('delete from public.transactions'),e=>e.code==='55000');
// Reapplying both migrations must not restore spent money or overwrite supplier state.
await db.exec("update public.stores set cash_kurus=800000; update public.products set system_stock=17 where id='00000000-0000-4000-8000-000000000001'");
await db.exec(core);await db.exec(seed);
assert.equal(await count('transactions'),2);assert.equal(await count('stores'),2);
assert.equal((await db.query('select min(cash_kurus) n from public.stores')).rows[0].n,800000);
assert.equal((await db.query("select system_stock from public.products where id='00000000-0000-4000-8000-000000000001'")).rows[0].system_stock,17);
const s=(await db.query('select id from public.stores where user_id=$1',[uid1])).rows[0].id;
await assert.rejects(()=>db.query('insert into public.inventory values($1,$2,-1,100,now())',[s,'00000000-0000-4000-8000-000000000001']),e=>e.code==='23514');
await db.query('insert into public.inventory values($1,$2,2,85000,now())',[s,'00000000-0000-4000-8000-000000000001']);
await asUser(uid2);assert.equal(await count('inventory'),0);
await asUser(uid1);assert.equal(await count('inventory'),1);
assert.equal((await db.query('select public.my_net_worth_kurus() n')).rows[0].n,'1038000');
// Inactive owned products remain part of server-side valuation.
await db.exec('reset role');
await db.exec("update public.products set active=false where id='00000000-0000-4000-8000-000000000001'");
await asUser(uid1);
assert.equal((await db.query('select public.my_net_worth_kurus() n')).rows[0].n,'1038000');
assert.equal(await count('products'),49);
await db.exec('reset role');
await assert.rejects(()=>db.query("insert into public.transactions(user_id,store_id,type,amount_kurus,balance_after_kurus,idempotency_key) values($1,$2,'REWARD',1,1,'wrong-owner')",[uid2,s]),e=>e.code==='23503');
// Unique indexes arbitrate conflicting identities, including case differences.
await asUser(uid3);await db.query('select public.complete_store_onboarding($1,$2)',['third','Third Store']);
await asUser(uid4);await assert.rejects(()=>db.query('select public.complete_store_onboarding($1,$2)',['fourth','THIRD STORE']),e=>e.code==='23505');
await db.exec('reset role');assert.equal(await count('stores'),3);assert.equal(await count('transactions'),3);
console.log('PASS: PostgreSQL migrations/seed, legacy backfill, one-time capital, idempotency, ownership RLS, denied writes, anonymous RPC, duplicate names, rollback, immutable ledger, integer constraints, net worth and safe reruns.');
console.log('Local auth.uid emulation only; actual Supabase and independent-session concurrency still need live verification.');
// Dashboard snapshot uses server day boundaries, excludes initial capital from revenue.
const dashboardSQL=await readFile('supabase/migrations/003_dashboard.sql','utf8');
await db.exec(dashboardSQL);await db.exec(dashboardSQL);
await asUser(uid1);
let snapshot=(await db.query('select public.my_dashboard() data')).rows[0].data;
assert.equal(snapshot.cash_kurus,'800000');assert.equal(snapshot.net_worth_kurus,'1038000');
assert.equal(snapshot.revenue_kurus,'0');assert.equal(snapshot.profit_kurus,'0');assert.equal(snapshot.orders,'0');
assert.equal(snapshot.inventory_units,'2');assert.equal(snapshot.history.length,7);assert.equal(snapshot.activity.length,1);
await db.exec('reset role');
await db.query("insert into public.transactions(user_id,store_id,type,amount_kurus,balance_after_kurus,idempotency_key) values($1,$2,'NPC_SALE',125000,925000,'dashboard-sale')",[uid1,s]);
await db.query("insert into public.transactions(user_id,store_id,type,amount_kurus,balance_after_kurus,idempotency_key,created_at) values($1,$2,'NPC_SALE',75000,925000,'yesterday-sale',(date_trunc('day',now() at time zone 'Europe/Istanbul') at time zone 'Europe/Istanbul')-interval '1 minute')",[uid1,s]);
await asUser(uid1);snapshot=(await db.query('select public.my_dashboard() data')).rows[0].data;
assert.equal(snapshot.revenue_kurus,'125000');assert.equal(snapshot.orders,'1');assert.equal(snapshot.profit_kurus,null);
assert.equal(snapshot.history[6].revenue_kurus,'125000');assert.equal(snapshot.history[5].revenue_kurus,'75000');
await asUser(uid2);snapshot=(await db.query('select public.my_dashboard() data')).rows[0].data;
assert.equal(snapshot.inventory_units,'0');assert.equal(snapshot.revenue_kurus,'0');assert.equal(snapshot.store_name,'Second Store');
await asUser(uid4);await assert.rejects(()=>db.query('select public.my_dashboard()'),e=>e.code==='P0002');
await asUser('');await assert.rejects(()=>db.query('select public.my_dashboard()'),e=>e.code==='28000');
await asUser('','anon');await assert.rejects(()=>db.query('select public.my_dashboard()'),e=>e.code==='42501');
console.log('PASS: dashboard snapshot, own-store isolation, inactive inventory valuation, no-sales zero values, unknown cost/profit, Istanbul day boundary, 7-day history, no-store/auth rejection, safe migration rerun.');
// Phase 4 fixtures exist only in this local test DB.
await db.exec('reset role');
const wholesaleSQL=await readFile('supabase/migrations/004_wholesale.sql','utf8');
await db.exec(wholesaleSQL);await db.exec(wholesaleSQL);
const product='00000000-0000-4000-8000-000000000001';
const request='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
await db.exec("update public.products set active=true,system_stock=20 where id='00000000-0000-4000-8000-000000000001'");
await asUser(uid1);
assert.equal((await db.query('select public.wholesale_catalog() data')).rows[0].data.length,50);
async function purchase(q=2,price=85000,key=request,id=product){return (await db.query('select public.buy_wholesale($1,$2,$3,$4) data',[id,q,price,key])).rows[0].data;}
const receipt=await purchase();assert.equal(receipt.total_kurus,'170000');assert.equal(receipt.balance_after_kurus,'630000');
assert.equal((await db.query('select quantity from public.inventory')).rows[0].quantity,4);
assert.equal((await db.query('select average_cost_kurus from public.inventory')).rows[0].average_cost_kurus,85000);
assert.deepEqual(await purchase(),receipt);
// Simultaneous JS submissions are queued by PGlite; checks request replay, not independent PostgreSQL sessions.
const repeats=await Promise.all([purchase(),purchase(),purchase()]);for(const result of repeats)assert.deepEqual(result,receipt);
assert.equal((await db.query('select cash_kurus from public.stores')).rows[0].cash_kurus,630000);
await assert.rejects(()=>purchase(1),e=>e.code==='W0008');
await assert.rejects(()=>purchase(-1),e=>e.code==='W0003');
await assert.rejects(()=>purchase(0),e=>e.code==='W0003');
await assert.rejects(()=>purchase(1001),e=>e.code==='W0003');
await assert.rejects(()=>purchase(1,1,'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'),e=>e.code==='W0007');
await assert.rejects(()=>purchase(19,85000,'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'),e=>e.code==='W0004');
await assert.rejects(()=>purchase(8,85000,'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'),e=>e.code==='W0005');
await assert.rejects(()=>purchase(1,85000,'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','ffffffff-ffff-4fff-8fff-ffffffffffff'),e=>e.code==='W0002');
assert.equal(await count('wholesale_receipts'),1);
await assert.rejects(()=>db.exec('delete from public.wholesale_receipts'),e=>e.code==='42501');
await db.exec('reset role');await db.query('update public.stores set warehouse_capacity=4 where id=$1',[s]);
await asUser(uid1);await assert.rejects(()=>purchase(1,85000,'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'),e=>e.code==='W0006');
// Higher purchase price: weighted average must include existing stock and prior cost.
await db.exec('reset role');await db.query('update public.stores set warehouse_capacity=50 where id=$1',[s]);
await db.query('update public.products set wholesale_price_kurus=90000 where id=$1',[product]);
await asUser(uid1);await purchase(2,90000,'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb');
assert.equal((await db.query('select average_cost_kurus from public.inventory')).rows[0].average_cost_kurus,86667);
assert.equal((await db.query('select cash_kurus from public.stores')).rows[0].cash_kurus,450000);
await asUser(uid2);assert.equal(await count('wholesale_receipts'),0);
await asUser(uid4);await assert.rejects(()=>purchase(),e=>e.code==='W0001');
await asUser('');await assert.rejects(()=>purchase(),e=>e.code==='28000');
await asUser('','anon');await assert.rejects(()=>purchase(),e=>e.code==='42501');
await db.exec('reset role');
assert.equal((await db.query('select system_stock from public.products where id=$1',[product])).rows[0].system_stock,16);
await assert.rejects(()=>db.exec('delete from public.wholesale_receipts'),e=>e.code==='55000');
await db.query('update public.products set active=false where id=$1',[product]);
await asUser(uid1);await assert.rejects(()=>purchase(1,90000,'cccccccc-cccc-4ccc-8ccc-cccccccccccc'),e=>e.code==='W0002');
assert.equal((await db.query('select cash_kurus from public.stores')).rows[0].cash_kurus,450000);
// A ledger failure after debit/stock/inventory writes must roll the entire RPC back.
await db.exec('reset role');await db.query('update public.products set active=true where id=$1',[product]);
await db.exec("create function public.test_reject_purchase() returns trigger language plpgsql as $$ begin if new.type='WHOLESALE_PURCHASE' then raise exception 'test ledger failure' using errcode='P0001'; end if; return new; end; $$; create trigger test_reject_purchase before insert on public.transactions for each row execute function public.test_reject_purchase();");
await asUser(uid1);await assert.rejects(()=>purchase(1,90000,'cccccccc-cccc-4ccc-8ccc-cccccccccccc'),e=>e.code==='P0001');
assert.equal((await db.query('select cash_kurus from public.stores')).rows[0].cash_kurus,450000);
assert.equal((await db.query('select quantity from public.inventory')).rows[0].quantity,6);
assert.equal(await count('wholesale_receipts'),2);
console.log('PASS: wholesale happy path, stock/funds/capacity/quantity/auth checks, price changes, weighted cost, duplicate requests, payload mismatch, receipt RLS and full rollback. Independent-session concurrency remains a live deployment check.');
await db.exec('reset role');
const inventorySQL=await readFile('supabase/migrations/005_inventory.sql','utf8');await db.exec(inventorySQL);await db.exec(inventorySQL);
await db.query('update public.products set active=false,market_price_kurus=80000 where id=$1',[product]);
await asUser(uid1);let inv=(await db.query('select public.my_inventory() data')).rows[0].data;
assert.equal(inv.units,'6');assert.equal(inv.cost_kurus,'520002');assert.equal(inv.value_kurus,'480000');assert.equal(inv.potential_profit_kurus,'-40002');
assert.equal(inv.items[0].active,false);assert.equal(inv.items[0].average_cost_kurus,'86667');
await asUser(uid2);inv=(await db.query('select public.my_inventory() data')).rows[0].data;assert.equal(inv.units,'0');assert.deepEqual(inv.items,[]);
await asUser(uid4);await assert.rejects(()=>db.query('select public.my_inventory()'),e=>e.code==='P0002');
await asUser('');await assert.rejects(()=>db.query('select public.my_inventory()'),e=>e.code==='28000');
await asUser('','anon');await assert.rejects(()=>db.query('select public.my_inventory()'),e=>e.code==='42501');
console.log('PASS: inventory ownership, empty inventory, weighted-cost values, inactive products, negative potential profit, auth rejection and repeat migration.');
await db.exec('reset role');
const npcSQL=await readFile('supabase/migrations/006_npc_sales.sql','utf8');await db.exec(npcSQL);await db.exec(npcSQL);
const secondStore=(await db.query('select id from public.stores where user_id=$1',[uid2])).rows[0].id;
await db.query('insert into public.inventory(store_id,product_id,quantity,average_cost_kurus) values($1,$2,2,100)',[secondStore,product]);
await db.query('update public.products set demand=100 where id=$1',[product]);
await asUser(uid2);
await assert.rejects(()=>db.query('select public.set_npc_listing($1,0,true)',[product]),e=>e.code==='N0001');
await assert.rejects(()=>db.query('select public.set_npc_listing($1,100,true)',['00000000-0000-4000-8000-000000000002']),e=>e.code==='N0002');
await db.query('select public.set_npc_listing($1,1,true)',[product]);
let tick=(await db.query('select public.process_npc_sales() data')).rows[0].data;assert.equal(tick.sold,0);assert.equal(tick.wait_seconds,60);
await db.exec('reset role');await db.query("update public.stores set last_npc_tick_at=now()-interval '61 seconds' where id=$1",[secondStore]);
await asUser(uid2);tick=(await db.query('select public.process_npc_sales() data')).rows[0].data;
assert.equal(tick.sold,1);assert.equal(tick.revenue_kurus,'1');assert.equal(tick.profit_kurus,'-99');
assert.equal((await db.query('select public.process_npc_sales() data')).rows[0].data.sold,0);
let sales=(await db.query('select public.my_sales_state() data')).rows[0].data;assert.equal(sales.orders.length,1);assert.equal(sales.items[0].quantity,1);
snapshot=(await db.query('select public.my_dashboard() data')).rows[0].data;assert.equal(snapshot.profit_kurus,'-99');assert.equal(snapshot.orders,'1');
await db.exec('reset role');await db.query("update public.stores set last_npc_tick_at=now()-interval '1 day' where id=$1",[secondStore]);
await asUser(uid2);assert.equal((await db.query('select public.process_npc_sales() data')).rows[0].data.sold,0);
await db.exec('reset role');await db.query("update public.stores set last_npc_tick_at=now()-interval '61 seconds' where id=$1",[secondStore]);
await asUser(uid2);assert.equal((await db.query('select public.process_npc_sales() data')).rows[0].data.sold,1);
assert.equal((await db.query('select enabled from public.npc_listings')).rows[0].enabled,false);
await asUser(uid1);sales=(await db.query('select public.my_sales_state() data')).rows[0].data;assert.equal(sales.orders.length,2);assert.equal(sales.orders[0].profit_kurus,null);
await asUser('');await assert.rejects(()=>db.query('select public.process_npc_sales()'),e=>e.code==='28000');
await asUser('','anon');await assert.rejects(()=>db.query('select public.my_sales_state()'),e=>e.code==='42501');
console.log('PASS: NPC price/ownership checks, server cooldown, no offline catch-up, atomic stock/ledger/COGS, negative realized profit, sold-out pause, history ownership and legacy unknown cost.');
await db.exec('reset role');
await db.query('update public.inventory set quantity=1 where store_id=$1 and product_id=$2',[secondStore,product]);
await db.query('update public.stores set listing_limit=1 where id=$1',[secondStore]);
await db.query('insert into public.inventory(store_id,product_id,quantity,average_cost_kurus) values($1,$2,1,100)',[secondStore,'00000000-0000-4000-8000-000000000002']);
await asUser(uid2);await db.query('select public.set_npc_listing($1,1,true)',[product]);
await assert.rejects(()=>db.query('select public.set_npc_listing($1,1,true)',['00000000-0000-4000-8000-000000000002']),e=>e.code==='N0003');
await db.exec('reset role');await db.query('update public.products set demand=0 where id=$1',[product]);
await db.query("update public.stores set last_npc_tick_at=now()-interval '61 seconds' where id=$1",[secondStore]);
await asUser(uid2);assert.equal((await db.query('select public.process_npc_sales() data')).rows[0].data.sold,0);
await db.exec('reset role');await db.query('update public.products set demand=100 where id=$1',[product]);
await db.query("update public.stores set last_npc_tick_at=now()-interval '61 seconds' where id=$1",[secondStore]);
await db.exec("create function public.test_reject_npc() returns trigger language plpgsql as $$ begin if new.type='NPC_SALE' then raise exception 'NPC ledger failure' using errcode='P0001'; end if; return new; end; $$; create trigger test_reject_npc before insert on public.transactions for each row execute function public.test_reject_npc();");
const before=(await db.query('select cash_kurus,reputation,last_npc_tick_at from public.stores where id=$1',[secondStore])).rows[0];
await asUser(uid2);await assert.rejects(()=>db.query('select public.process_npc_sales()'),e=>e.code==='P0001');
assert.deepEqual((await db.query('select cash_kurus,reputation,last_npc_tick_at from public.stores')).rows[0],before);
assert.equal((await db.query('select quantity from public.inventory where product_id=$1',[product])).rows[0].quantity,1);
console.log('PASS: NPC listing limit, zero-demand no-sale and complete rollback of clock/cash/stock/reputation on ledger error.');
await db.exec('reset role');
const marketSQL=await readFile('supabase/migrations/007_marketplace.sql','utf8');await db.exec(marketSQL);await db.exec(marketSQL);
const thirdStore=(await db.query('select id from public.stores where user_id=$1',[uid3])).rows[0].id;
await db.query('insert into public.inventory(store_id,product_id,quantity,average_cost_kurus) values($1,$2,3,10000)',[thirdStore,product]);
await asUser(uid3);
const priorWorth=(await db.query('select public.my_net_worth_kurus() n')).rows[0].n;
const listingRequest='dddddddd-dddd-4ddd-8ddd-dddddddddddd';
async function createMarket(q=2,price=20000,key=listingRequest){return (await db.query('select public.create_marketplace_listing($1,$2,$3,$4) id',[product,q,price,key])).rows[0].id;}
const marketListing=await createMarket();assert.equal(await createMarket(),marketListing);
assert.equal((await db.query('select reserved_quantity from public.inventory')).rows[0].reserved_quantity,2);
assert.equal((await db.query('select public.my_net_worth_kurus() n')).rows[0].n,priorWorth);
await assert.rejects(()=>createMarket(3),e=>e.code==='M0008');
await assert.rejects(()=>db.query('select public.set_npc_listing($1,100,true)',['00000000-0000-4000-8000-000000000002']),e=>e.code==='N0002');
const buyRequest='eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee';
async function marketBuy(q=2,price=20000,key=buyRequest,id=marketListing){return (await db.query('select public.buy_marketplace_listing($1,$2,$3,$4) data',[id,q,price,key])).rows[0].data;}
await assert.rejects(()=>marketBuy(),e=>e.code==='M0007');
await asUser(uid2);await assert.rejects(()=>db.query('select public.cancel_marketplace_listing($1)',[marketListing]),e=>e.code==='M0004');
await assert.rejects(()=>marketBuy(0),e=>e.code==='M0001');await assert.rejects(()=>marketBuy(3),e=>e.code==='M0005');await assert.rejects(()=>marketBuy(2,1),e=>e.code==='M0006');
await db.exec('reset role');await db.query('update public.stores set warehouse_capacity=2 where id=$1',[secondStore]);
await asUser(uid2);await assert.rejects(()=>marketBuy(),e=>e.code==='W0006');
await db.exec('reset role');await db.query('update public.stores set warehouse_capacity=50 where id=$1',[secondStore]);
await asUser(uid2);const marketReceipt=await marketBuy();assert.equal(marketReceipt.total_kurus,'40000');assert.equal(marketReceipt.fee_kurus,'2000');assert.equal(marketReceipt.seller_gets_kurus,'38000');
assert.deepEqual(await marketBuy(),marketReceipt);for(const result of await Promise.all([marketBuy(),marketBuy()]))assert.deepEqual(result,marketReceipt);
await assert.rejects(()=>marketBuy(1),e=>e.code==='M0008');await assert.rejects(()=>marketBuy(1,20000,'ffffffff-ffff-4fff-8fff-ffffffffffff'),e=>e.code==='M0005');
assert.equal((await db.query('select quantity from public.inventory where product_id=$1',[product])).rows[0].quantity,3);
assert.equal((await db.query('select average_cost_kurus from public.inventory where product_id=$1',[product])).rows[0].average_cost_kurus,13367);
await asUser(uid3);snapshot=(await db.query('select public.my_dashboard() data')).rows[0].data;assert.equal(snapshot.revenue_kurus,'40000');assert.equal(snapshot.profit_kurus,'18000');assert.equal(snapshot.orders,'1');
assert.equal((await db.query('select cash_kurus from public.stores')).rows[0].cash_kurus,1038000);
const cancelled=await createMarket(1,25000,'ffffffff-ffff-4fff-8fff-ffffffffffff');await db.query('select public.cancel_marketplace_listing($1)',[cancelled]);await db.query('select public.cancel_marketplace_listing($1)',[cancelled]);
assert.equal((await db.query('select reserved_quantity from public.inventory')).rows[0].reserved_quantity,0);
await assert.rejects(()=>db.exec('update public.marketplace_listings set quantity=100'),e=>e.code==='42501');
const finalListing=await createMarket(1,1000000000000,'abababab-abab-4aba-8aba-abababababab');
await asUser(uid2);await assert.rejects(()=>marketBuy(1,1000000000000,'cdcdcdcd-cdcd-4cdc-8cdc-cdcdcdcdcdcd',finalListing),e=>e.code==='W0005');
await asUser(uid3);await db.query('select public.cancel_marketplace_listing($1)',[finalListing]);
const rollbackListing=await createMarket(1,25000,'bcbcbcbc-bcbc-4bcb-8bcb-bcbcbcbcbcbc');
await db.exec('reset role');await db.exec("create function public.test_reject_market() returns trigger language plpgsql as $$ begin if new.type='MARKETPLACE_SALE' then raise exception 'Market ledger failure' using errcode='P0001'; end if; return new; end; $$; create trigger test_reject_market before insert on public.transactions for each row execute function public.test_reject_market();");
const balances=(await db.query('select id,cash_kurus from public.stores order by id')).rows;
await asUser(uid2);await assert.rejects(()=>marketBuy(1,25000,'cacacaca-caca-4cac-8cac-cacacacacaca',rollbackListing),e=>e.code==='P0001');
await db.exec('reset role');assert.deepEqual((await db.query('select id,cash_kurus from public.stores order by id')).rows,balances);assert.equal(await count('marketplace_receipts'),1);
assert.equal((await db.query('select quantity from public.marketplace_listings where id=$1',[rollbackListing])).rows[0].quantity,1);
await asUser(uid4);await assert.rejects(()=>db.query('select public.my_marketplace()'),e=>e.code==='P0002');
await asUser('');await assert.rejects(()=>db.query('select public.my_marketplace()'),e=>e.code==='28000');await asUser('','anon');await assert.rejects(()=>db.query('select public.my_marketplace()'),e=>e.code==='42501');
console.log('PASS: marketplace reservation/cancel, ownership/auth, self-buy rejection, partial/full stock checks, fee ledger, realized net profit, weighted buyer cost, idempotency, sold-out rejection, funds/capacity and full rollback. PGlite queues concurrent calls; independent-session race test still required.');
await db.close();
